# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
